---
title: "Additional information"
author: "Oscar Villarreal"
date: "5/16/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,eval=FALSE)
```

# R package preparation and installation:

```{r}
## CREATE PACKAGE

### Empty package:
File->New project->New directory->R package

### Save data to the data/ directory automatically:
devtools::use_data(data1, overwrite=T)

## RCPP

### After creating the package, run this:
devtools::use_rcpp()

### Then add the following lines (where “packageName” is the name of your package) in any R script which is inside the R/ directory (e.g. main.R):
#' @useDynLib packageName
#' @importFrom Rcpp sourceCpp
NULL

## Edit the NAMESPACE file:

### First run the following (if it complains, make sure the working directory is set to the package directory, delete the NAMESPACE file and retry):
devtools::document()

### Add the following line to the NAMESPACE file if it is missing (otherwise the files in the R/ directory will not load):
exportPattern("^[[:alpha:]]+")

### Also add the following lines if they are missing:
importFrom(Rcpp,sourceCpp)
import(Rcpp)
useDynLib(packageName)

## Edit the DESCRIPTION file:

### Make sure it contains the following lines:
LinkingTo: Rcpp
Imports: Rcpp

### Edit the cpp codes in the /src directory. There are two ways of calling cpp code from an R script:
http://dirk.eddelbuettel.com/code/rcpp/Rcpp-modules.pdf 

# The first way (harder) is to use the language of Rcpp, so that it is automatically exported to any R script, for example in the following program:

#include <Rcpp.h>
using namespace Rcpp;
// [[Rcpp::export]]
NumericMatrix calc_distances(NumericMatrix pos, NumericMatrix neg) {
  int npos=pos.nrow(), nneg=neg.nrow(), nday0=pos.ncol();
  NumericMatrix out(npos,nneg);
  for(int i=0; i<npos; i++) //Rcout<<i<<std::endl;
    for(int j=0; j<nneg; j++)
      for(int k=0; k<nday0; k++)
        out(i,j) += pow(pos(i,k)-neg(j,k), 2);
  return out;
}

# The second way (easier) is to create an Rcpp module which translates specific functions to the language of Rcpp automatically (i.e. the function which you can call from any R script), for example in the following program:

#include<math.h>
double test(double x, double y) {
  return sqrt( x*x + y*y );
}
#include <Rcpp.h>
RCPP_MODULE(mod) {
  using namespace Rcpp;
  Rcpp::function("test",&test);
}

# If you use the second way, you need to add the following line to any R script which is inside the R/ directory (e.g. main.R):
loadModule("mod",TRUE)

# If C++11 does not work, run this command before building the package:
Sys.setenv("PKG_CXXFLAGS"="-std=c++11")
# In order to use C++11 code in a package, the package’s "src/Makevars"" file (or src/Makevars.win on Windows) should include the line (http://web.mit.edu/r_v3.3.1/R-exts.pdf):
CXX_STD = CXX11

# To generate the manual annotation files of all functions:
roxygen2::roxygenise()

# Pandoc must be installed if you want to generate html or pdf reports. Rstudio already comes with pandoc installed; but if you want to use MoPAC in R outside of Rstudio, you need to either install pandoc (sudo yum install pandoc) or set the path to the Rstudio installation of pandoc:
Sys.getenv("RSTUDIO_PANDOC") #run this inside Rstudio to get pandoc installation of Rstudio
Sys.setenv(RSTUDIO_PANDOC="/usr/lib/rstudio-server/bin/pandoc") #run this in R before calling MoPAC

# To add data to the package:
devtools::use_data(data1, overwrite=T)
# then write the documentation of each dataset in the file R/data.R
# then, to use the data inside MoPAC functions: MoPAC::essentials

# In the terminal, where the main package directory is located (i.e. at ../MoPAC) run:
R CMD check MoPAC & disown
# This will create a directory called "MoPAC.Rcheck" containing the manual pdf.
# To avoid an example from running:
#' \dontrun{
#' }

# Required R packages:
install.packages("Rcpp")
install.packages("gtools")
install.packages("stringr")
install.packages("openxlsx")
install.packages("tensorA")
install.packages("ineq")
install.packages("reshape2")
install.packages("plyr")
install.packages("ggplot2")
install.packages("gplots")
install.packages("ggrepel")
install.packages("gridExtra")
install.packages("knitr")
install.packages("rmarkdown")
install.packages("shiny")
install.packages("shinyBS")
install.packages("shinythemes")
install.packages("shinyFiles")
install.packages("DT")
install.packages("visNetwork")
install.packages("sqldf")
install.packages("rhandsontable")
install.packages("neat")
install.packages("igraph")
# base: utils, stats, tools, grid

# Optional R packages:
install.packages("plotly")
source("https://bioconductor.org/biocLite.R")
biocLite("STRINGdb")
# These packages might require additional software in order to be installed, which is why I did not put them in the required list:
sudo yum install libpng-devel
sudo yum install openssl-devel
sudo yum install libcurl-devel

# Optional software for pdf rendering:
sudo yum install pandoc

# Install MoPAC:
install.packages("/home/oscar/Downloads/MoPAC_0.1.0.tar.gz", repos = NULL, type="source")
sudo su - -c "R -e \"install.packages('/home/ovillarreal/MoPAC_0.1.0.tar.gz',repos=NULL,type='source')\""
sudo su odvillarreal -c "R -e \"install.packages('/Users/odvillarreal/Documents/feb4/MoPAC_0.3.0.tar.gz',repos=NULL,type='source')\""

# Debugging:
library(Rcpp)
library(MoPAC)
source("~/MoPAC/R/plotting.R")
sourceCpp("~/MoPAC/src/sort.cpp")
sourceCpp("~/MoPAC/src/rra2tail.cpp")
sourceCpp("~/MoPAC/src/quantile.cpp")
sourceCpp("~/MoPAC/src/aliases.cpp")

```

# STRINGdb datasets pre-processing (takes more than two minutes to do this 2:10):

```{r}
library(STRINGdb)
# a) get_aliases():
proteinsDf <- read.table("~/tools/neat/9606__proteins.tsv",
  sep = "\t", header = TRUE,stringsAsFactors = FALSE, fill = TRUE, quote="")
# proteinsDf <- read.table("/home/ovillarreal/correlations/9606__proteins.tsv.gz", 
#   sep = "\t", header = TRUE,stringsAsFactors = FALSE, fill = TRUE, quote="")
proteins = subset(proteinsDf, select = c("protein_external_id", 
    "preferred_name", "protein_size", "annotation"))
aliasDf <- read.table("~/tools/neat/9606__protein_aliases_tf.tsv",
  sep="\t",header=TRUE,quote="",stringsAsFactors=FALSE,fill=TRUE)
# aliasDf <- read.table("/home/ovillarreal/correlations/9606__protein_aliases_tf.tsv.gz",
#   sep="\t",header=TRUE,quote="",stringsAsFactors=FALSE,fill=TRUE)
aliasDf = renameColDf(aliasDf, "protein_id", "STRING_id")
aliasDf = subset(aliasDf, select = c("STRING_id", "alias"))
pr1 = data.frame(STRING_id = proteins$protein_external_id,
  alias = proteins$preferred_name, stringsAsFactors = FALSE)
pr2 = data.frame(STRING_id = proteins$protein_external_id,
  alias = proteins$protein_external_id, stringsAsFactors = FALSE)
pr3 = data.frame(STRING_id = proteins$protein_external_id,
  alias = unlist(strsplit(proteins$protein_external_id,
  "\\."))[seq(from = 2, to = 2 * nrow(proteins), by = 2)],stringsAsFactors = FALSE)
aliasDf = subset(aliasDf, !(toupper(iconv(alias, "WINDOWS-1252", 
  "UTF-8")) %in% toupper(proteins$preferred_name)) & 
  !(toupper(iconv(alias, "WINDOWS-1252", "UTF-8")) %in% 
      toupper(proteins$protein_external_id)) & !(toupper(iconv(alias, 
  "WINDOWS-1252", "UTF-8")) %in% toupper(unlist(strsplit(proteins$protein_external_id, 
  "\\."))[seq(from = 2, to = 2 * nrow(proteins), by = 2)])))
aliasDf2 <- unique(rbind(pr1, pr2, pr3, aliasDf))
aliasDf2 <- aliasDf2[,c("alias","STRING_id")]
aliasDf2 <- aliasDf2[order(aliasDf2$alias),]
aliasDf2 <- aliasDf2[!duplicated(aliasDf2$alias),]
# utils::write.table(aliasDf2$alias,"aliases_apr10.txt",quote=FALSE,sep='\t',row.names=FALSE,col.names=FALSE)
# utils::write.table(aliasDf2$STRING_id,"ids_apr10.txt",quote=FALSE,sep='\t',row.names=FALSE,col.names=FALSE)
# utils::write.csv(aliasDf2,"aliases_apr10.csv",quote=FALSE,row.names=FALSE)

# b) load():
library(igraph)
PPI <- read.table("~/tools/neat/9606__protein_links.tsv", 
  sep = " ", header = TRUE, stringsAsFactors = FALSE, fill = TRUE)
# PPI <- read.table("/home/ovillarreal/correlations/9606.protein.links.full.v11.0.txt.gz",
#   sep = " ", header = TRUE, stringsAsFactors = FALSE, fill = TRUE)
# PPI <- read.table("/home/ovillarreal/correlations/9606.protein.links.detailed.v11.0.txt.gz",
#   sep = " ", header = TRUE, stringsAsFactors = FALSE, fill = TRUE)
# PPIselected <- PPI[PPI$experiments > 0 | PPI$experiments_transferred > 0, c("protein1","protein2","experiments","experiments_transferred")]
# PPIselected <- PPI[PPI$experimental > 0, c("protein1","protein2","experimental")]
# colnames(PPIselected)[1] <- "STRING_id"
# colnames(aliasDf2)[2] <- "gene1"
# PPIselected1 <- merge(aliasDf2,PPIselected)

# graph = graph.data.frame(PPIselected, FALSE)
# c) get_enrichment():
# ann = read.table("~/tools/neat/annotations_9606.tsv",
#   sep="\t",stringsAsFactors=FALSE,quote="",fill=TRUE,header=FALSE)
ann = read.table("/home/ovillarreal/correlations/annotations_9606.tsv.gz",
  sep="\t",stringsAsFactors=FALSE,quote="",fill=TRUE,header=FALSE)
ann = renameColDf(ann, "V1", "STRING_id")
ann = renameColDf(ann, "V2", "term_id")
ann = renameColDf(ann, "V3", "category")
ann <- unique(renameColDf(ann, "V4", "type"))
annDesc <- read.table("~/tools/neat/annotations_description.tsv", sep = "\t",
            header = TRUE, quote = "", fill = TRUE, stringsAsFactors = FALSE)
# annDesc <- read.table("/home/ovillarreal/correlations/annotations_description.tsv.gz", sep = "\t", 
#             header = TRUE, quote = "", fill = TRUE, stringsAsFactors = FALSE)


stringdb_9606 <- list(Proteins=proteins,Aliases=aliasDf2,Annotation=ann,Description=annDesc,PPI=PPI)
# stringdb_9606 <- list(Proteins=proteins,Aliases=aliasDf2,Annotation=ann,Description=annDesc,Graph=graph)
devtools::use_data(stringdb_9606, overwrite=T)
```











