#' @title Gene differential essentiality scoring.
#'
#' @description Normalizes the distributions of one pair of conditions and generates differential gene essentiality scores.
#'
#' @param id an optional identifier for the analysis. All input will be read from and all output will be stored in a directory with this name. If \code{NULL}, two data frames must be supplied containing the counts and annotation. Defaults to \code{NULL}.
#' @param sgRNA an optional data frame containing the sgRNA-level log-fold-changes for the replicate-averaged conditions. If \code{NULL}, the file 'sgRNA_lfc.txt' generated previously will be read.
#' @param gene_reps an optional data frame containing the gene-level scores for each replicate. If \code{NULL}, the file 'gene_reps.txt' generated previously will be read.
#' @param gene gene-level replicate-averaged log-fold-changes
#' @param annotation an optional data frame containing the sample annotation information. If \code{NULL}, the annotation file generated previously will be read.
#' @param condition1 name of first condition (i.e. any of the column names in the gene_lfc.txt file). Defaults to the first condition.
#' @param condition2 name of second condition (i.e. any of the column names in the gene_lfc.txt file). Defaults to the second condition.
#' @param read.unenriched logical. Should the filtered list of unenriched genes generated by the 2-tail RRA algorithm be used to perform the normalization? Requires an identifier to be set, otherwise please use \code{unenriched} instead. Defaults to \code{FALSE}.
#' @param unenriched an optional vector of names for filtered unenriched genes. Use it instead of \code{read.unenriched} when the \code{id} is set to \code{NULL}. Defaults to \code{NULL}.
#' @param report logical. Should an html report of top-ranking differentially essential genes be generated? Requires an identifier to be set, and both pandoc and plotly installation. Defaults to \code{FALSE}.
#' @param shinyF logical. An internal parameter used by the graphical user interface. If using command-line leave as \code{NULL}.
#'
#' @details
#' The distributions of gene scores are first normalized in the following way: (1) If \code{read.unenriched} is \code{FALSE}, then the combination of essential and nonessential genes are quantile-normalized; if it is \code{TRUE}, then the unenriched genes are quantile-normalized, this is recommended if the amount of controls is small. (2) A quantile-quantile plot is fitted to the transformation before and after the normalization. (3) A smoothing spline is fitted to the quantile-quantile plot. (4) The smoothing spline is used to interpolate the transformation of the gene scores which corresponds to the normalization of step 1.
#'
#' After the gene scores are normalized, a Z score is used to rank the genes according to differential essentiality between the two conditions. A P value is also obtained from the replicate information of each gene.
#'
#' If \code{id} is not \code{NULL}, the following files are produced in the directory with name equal to the identifier:
#' \itemize{
#'  \item{\code{condition1_condition2_normalized_reps.txt}, containing the gene-level normalized scores for the replicates of both conditions.}
#'  \item{\code{condition1_condition2_differential.txt}, the relative difference statistic for the pair of conditions selected.}
#' }
#'
#' @return A data frame containing the MoPAC differential gene essentiality scores of the two selected conditions.
#'
#' @author Oscar D Villarreal, \email{oscardvillarreal@gmail.com}
#' @keywords differential essentiality
#'
#' @examples
#'
#' ## Example I. Generating output files through an analysis identifier:
#'
#' ## 1. Prepare read counts information:
#' counts <- read.counts(id="DANG_CCK81", counts=MoPAC::dang_cck81, library=MoPAC::sgRNA_library)
#'
#' ## 2. Manually fill out either of the two annotation files produced by read.counts.
#' ## In this example we will fill it out using R:
#' annotation <- counts$Annotation
#' annotation$Condition <- c("Plasmid0","Plasmid1",rep("DANG",4),rep("CCK81",3))
#' annotation$Replicate <- c("A","A","A","B","C","D","A","B","C")
#' annotation$Control <- c("","",rep("Plasmid0",4),rep("Plasmid1",3))
#' utils::write.csv(annotation,"DANG_CCK81/annotation.csv",quote=FALSE,row.names=FALSE)
#'
#' ## 3. Get pre-processed fold changes:
#' qc <- quality.control(id="DANG_CCK81", report=FALSE)
#'
#' ## 4. Two-tail RRA essentiality analysis:
#' significance <- RRA.2tail(id="DANG_CCK81",annotation=annotation)
#'
#' ## 5. Gene differential essentiality analysis:
#' ## a) If there are only two conditions, there's no need to specify them:
#' differential <- analyze.differential(id="DANG_CCK81", read.unenriched=TRUE, report=FALSE)
#'
#' ## c) If there are more than two conditions, please select two of them explicitly:
#' differential <- analyze.differential(id="DANG_CCK81", read.unenriched=TRUE,
#'                 condition1="DANG", condition2="CCK81", report=FALSE)
#'
#' ## Example II. Returning a data frame without using an identifier to generate output:
#'
#' ## 1. Prepare read counts information:
#' counts <- read.counts(counts=MoPAC::dang_cck81, library=MoPAC::sgRNA_library)
#'
#' ## 2. Prepare sample annotation as a data frame:
#' annotation <- counts$Annotation
#' annotation$Condition <- c("Plasmid0","Plasmid1",rep("DANG",4),rep("CCK81",3))
#' annotation$Replicate <- c("A","A","A","B","C","D","A","B","C")
#' annotation$Control <- c("","",rep("Plasmid0",4),rep("Plasmid1",3))
#'
#' ## 3. Get pre-processed fold changes:
#' qc <- quality.control(counts=counts$Counts, annotation=annotation, report=FALSE)
#'
#' ## 4. Two-tail RRA essentiality analysis:
#' significance <- RRA.2tail(sgRNA_lfc_reps=qc$sgRNA_lfc_reps,gene_lfc_reps=qc$gene_lfc_reps,annotation=annotation)
#'
#' ## 5. Gene differential essentiality analysis:
#' ## a) If there are only two conditions, there's no need to specify them:
#' differential <- analyze.differential(gene_reps=significance$gene_lfc_reps,
#'    gene = significance$gene_lfc,
#'    sgRNA=significance$sgRNA_lfc, annotation=annotation,
#'    unenriched=significance$Unenriched, report=FALSE)
#'
#' ## b) If there are more than two conditions, please select two of them explicitly:
#' differential <- analyze.differential(gene_reps=significance$gene_lfc_reps,
#'    gene = significance$gene_lfc,condition1="DANG", condition2="CCK81",
#'    sgRNA=significance$sgRNA_lfc, annotation=annotation,
#'    unenriched=significance$Unenriched, report=FALSE)
#'
#' ##--------------------------------------------------------------------------------------
#'
#' @export
#'
library(Rcpp)
sourceCpp("src/quantile.cpp")

analyze.differential <- function(id=NULL,sgRNA1=NULL,sgRNA2=NULL,gene1=NULL,gene2=NULL,gene_reps1=NULL,gene_reps2=NULL, condition1=NULL,condition2=NULL,annotation=NULL,read.unenriched=FALSE,unenriched=NULL,report=FALSE,shinyF=NULL) {
  set.seed(12)
  print("Importing data...")
  if(!is.null(shinyF)) shinyF(0.2,message='Differential analysis',detail="Importing data...")
  
  # Read sgRNA-level replicate-averaged log-fold-changes ----------------------------------------------------
  if(is.null(id)) { # insufficient information provided
    stop("Please specify a working directory or provide the replicate-averaged sgRNA log-fold-changes.")
  } else { 
    # is a table of read sgRNA_reps available in the working directory?
    if(file.exists(file.path(id,condition1,"sgRNA_lfc.txt")) && file.exists(file.path(id,condition2,"sgRNA_lfc.txt"))) {
      sgRNA1 <- utils::read.table(file.path(id,condition1,"/sgRNA_lfc.txt"),header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
      sgRNA2 <- utils::read.table(file.path(id,condition2,"/sgRNA_lfc.txt"),header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
    } else if(is.data.frame(sgRNA1) && is.data.frame(sgRNA2)) { # was a data frame provided as a table of read counts?
      sgRNA1[,sapply(sgRNA1,is.factor)] <- sapply(sgRNA1[,sapply(sgRNA1,is.factor)],as.character)
      sgRNA2[,sapply(sgRNA2,is.factor)] <- sapply(sgRNA2[,sapply(sgRNA2,is.factor)],as.character)
    } else if(is.character(sgRNA1) && is.character(sgRNA2)){# was a file path provided?
      sgRNA1 <- utils::read.table(sgRNA1,header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
      sgRNA2 <- utils::read.table(sgRNA2,header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
    } else
      stop("sgRNA replicate-averaged log-fold-change file not found in the specified address.")
  } 
  
  if(!"sgRNA"%in%colnames(sgRNA1) | !"Gene"%in%colnames(sgRNA1))
    stop("Error: missing column in lfc files - 'sgRNA' or 'Gene'.")
  
  # Import gene_reps-level replicate-averaged log-fold-changes ----------------------------------------------------
  if(is.null(id)){ # insufficient information provided
    stop("Please specify a working directory or provide the gene log-fold-changes for each replicate.")
  } else {
    # is a table of read gene_reps available in the working directory?
     if(file.exists(file.path(id,condition1,"gene_lfc_reps.txt")) && file.exists(file.path(id,condition2,"gene_lfc_reps.txt"))) {
      gene_reps1 <- utils::read.table(file.path(id,condition1,"gene_lfc_reps.txt"),header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
      gene_reps2 <- utils::read.table(file.path(id,condition2,"gene_lfc_reps.txt"),header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
    } else if(is.data.frame(gene_reps1)) {
      gene_reps1[,sapply(gene_reps1,is.factor)] <- sapply(gene_reps1[,sapply(gene_reps1,is.factor)],as.character)
      gene_reps2[,sapply(gene_reps2,is.factor)] <- sapply(gene_reps2[,sapply(gene_reps2,is.factor)],as.character)
    } else if(is.character(gene_reps1)) { # was a file path provided?
      if(file.exists(gene_reps1)) {
        gene_reps1 <- utils::read.table(gene_reps1,header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
      } else stop("Gene log-fold-change file (Condition 1) per replicate not found in the specified address.")
    
      if(file.exists(gene_reps2)) {
        gene_reps2 <- utils::read.table(gene_reps2,header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
      } else stop("Gene log-fold-change file (Condition 2) per replicate not found in the specified address.")
    } else 
      stop("Please provide a valid table of gene log-fold-changes per replicate.")
  }
  
  if(!"Gene"%in%colnames(gene_reps1))
    stop("Error: missing column in gene_lfc_reps files - 'Gene'.")
  
    # Import Gene-level replicate-averaged log-fold-changes ----------------------------------------------------
  if(is.null(id)) { # insufficient information provided
    stop("Please specify a working directory or provide the replicate-averaged gene log-fold-changes.")
  } else{
    # is a table of read gene_reps available in the working directory?
    if(file.exists(file.path(id,condition1,"gene_lfc.txt"))) {
      gene1 <- utils::read.table(file.path(id,condition1,"gene_lfc.txt"),header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
      gene2 <- utils::read.table(file.path(id,condition2,"gene_lfc.txt"),header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
    } else if(is.data.frame(gene1)) {
      gene1[,sapply(gene1,is.factor)] <- sapply(gene1[,sapply(gene1,is.factor)],as.character)
      gene2[,sapply(gene2,is.factor)] <- sapply(gene2[,sapply(gene2,is.factor)],as.character)
    } else if(is.character(gene1)) { # was a file path provided?
      if(file.exists(gene1)) {
        gene1 <- utils::read.table(gene1,header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
      } else stop("Gene replicate-averaged log-fold-change file1 not found in the specified address.")
      if(file.exists(gene2)) {
        gene2 <- utils::read.table(gene2,header=TRUE,sep="\t",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE)
      } else stop("Gene replicate-averaged log-fold-change file2 not found in the specified address.")
    } else stop("Please provide a valid table of replicate-averaged gene log-fold-changes.")
  }
   
  if(!"Gene"%in%colnames(gene1))
    stop("Error: missing column in gene_lfc files - 'Gene'.")
  
  # Read annotation -------------------------------------------------------------------------
  if(is.null(id) & is.null(annotation)) { # insufficient information provided
    stop("Please specify a working directory or provide a data frame of annotation.")
  } else if(!is.null(id) & is.null(annotation)) { # is a table of annotation available in the working directory?
    if(file.exists(paste0(id,"/annotation.csv"))) {
      annotation0 <- utils::read.csv(paste0(id,"/annotation.csv"),header=TRUE,as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE,comment.char="",quote="\"",na.strings="")
      if(sum(is.na(annotation0[,-which(colnames(annotation0)%in%"Control")]))>0)
        annotation0 <- openxlsx::read.xlsx(paste0(id,"/annotation.xlsx"),check.names=FALSE,na.strings="")
      annotation0[annotation0 == ""] <- NA     
      if(sum(is.na(annotation0))>0)
        stop("Please fill out the sample file annotation before proceeding.")
    } else stop("Please provide a table of annotation or run the previous modules first.")
  } else if(is.data.frame(annotation)) { # was a data frame provided as a table of read counts?
    annotation0 <- annotation
    annotation0[,sapply(annotation0,is.factor)] <- sapply(annotation0[,sapply(annotation0,is.factor)],as.character)
  }  else if(is.character(annotation)) {
    if(file.exists(annotation)) {
      if(tools::file_ext(annotation)=="xlsx") {
        annotation0 <- openxlsx::read.xlsx(annotation,check.names=FALSE,na.strings="")
      } else if(tools::file_ext(annotation)=="csv") {
        annotation0 <- utils::read.csv(annotation,header=TRUE,as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE,comment.char="",quote="\"",na.strings="")
      } else annotation0 <- utils::read.table(annotation,header=TRUE,as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE,comment.char="",quote="\"",na.strings="")
    } else stop("Annotation file not found in the specified address.")
    
    annotation0[annotation0 == ""] <- NA     
    if(sum(is.na(annotation0))>0)
      stop("Please fill out the sample file annotation before proceeding.")
  } else stop("The annotation object provided could not be read.")
  
  if(sum(!c("Sample","Condition","Replicate")%in%colnames(annotation0))>0)
    stop("Please make sure the annotation contains the columns: Sample, Condition, Replicate")
  
  annotation1 <- annotation0[annotation0$Sample%in%c(colnames(gene_reps1),colnames(gene_reps2)),]
  if(nrow(annotation1)==0)
    stop("Mismatch found between the annotation samples and the sgRNA column names.")
  
  cond_group1 = unlist(stringr::str_split(condition1, "\\.vs\\."))[1]
  cond_group2 = unlist(stringr::str_split(condition2, "\\.vs\\."))[1]
  samples1 <- as.character(annotation1$Sample[annotation1$Condition==cond_group1])
  samples2 <- as.character(annotation1$Sample[annotation1$Condition==cond_group2])
  
  # Normalization  ---------------------------------------------------------------------------------------------------------
  # At the gene level the normalization is made before averaging the replicates, since the quality is better.
  # At the sgRNA level the normalization is made after averaging the replicates, since it is noisier.
  print("Normalizing conditions...")
  if(!is.null(shinyF)) shinyF(0.2,message='Differential analysis',detail="Normalizing conditions...")
  
  # Extract the unenriched or the control genes:
  if(!is.null(unenriched)) {
    gene_reps1 = gene_reps1[match(unenriched, gene_reps1$Gene),]
    gene_reps2 = gene_reps2[match(unenriched, gene_reps2$Gene),]
    gene_reps = cbind(gene_reps1[,which(colnames(gene_reps1)%in%c("Gene","Category")),drop=F],gene_reps1[,samples1,drop=F],gene_reps2[,samples2,drop=F])
    controls1 <- controls2 <- gene_reps[gene_reps$Gene%in%unenriched,c(samples1,samples2)]
    
    sgRNA1 = sgRNA1[match(unenriched, sgRNA1$Gene),]
    sgRNA2 = sgRNA2[match(unenriched, sgRNA2$Gene),]
    sgRNA = cbind(sgRNA1[,which(colnames(sgRNA1)%in%c("sgRNA","Gene","Category")),drop=F],sgRNA1[,cond_group1,drop=F],sgRNA2[,cond_group2,drop=F])
    controls1_sgRNA <- controls2_sgRNA <- sgRNA[sgRNA$Gene%in%unenriched,c(cond_group1,cond_group2)] #extract unenriched genes from input
    
  } else if(read.unenriched==TRUE) {
    if(!file.exists(file.path(id,condition1,"unenriched.txt")))
      stop(file.path(id,condition1,"unenriched.txt was not found."))
    if(!file.exists(file.path(id,condition2,"unenriched.txt")))
      stop(file.path(id,condition2,"unenriched.txt was not found."))
    
    unenriched1 <- utils::read.table(file.path(id,condition1,"unenriched.txt"),header=TRUE,sep="",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE,row.names=NULL)[,1]
    unenriched2 <- utils::read.table(file.path(id,condition2,"unenriched.txt"),header=TRUE,sep="",as.is=TRUE,check.names=FALSE,stringsAsFactors=FALSE,row.names=NULL)[,1]
    unenriched = intersect(unenriched1,unenriched2)
    
    gene_reps1 = gene_reps1[match(unenriched, gene_reps1$Gene),]
    gene_reps2 = gene_reps2[match(unenriched, gene_reps2$Gene),]
    gene_reps = cbind(gene_reps1[,which(colnames(gene_reps1)%in%c("Gene","Category")),drop=F],gene_reps1[,samples1,drop=F],gene_reps2[,samples2,drop=F])
    controls1 <- controls2 <- gene_reps[gene_reps$Gene%in%unenriched,c(samples1,samples2)]
    
    sgRNA1 = sgRNA1[match(unenriched, sgRNA1$Gene),]
    sgRNA2 = sgRNA2[match(unenriched, sgRNA2$Gene),]
    sgRNA = cbind(sgRNA1[,which(colnames(sgRNA1)%in%c("sgRNA","Gene","Category")),drop=F],sgRNA1[,cond_group1,drop=F],sgRNA2[,cond_group2,drop=F])
    controls1_sgRNA <- controls2_sgRNA <- sgRNA[sgRNA$Gene%in%unenriched,c(cond_group1,cond_group2)] #extract unenriched genes from input
    
  } else stop("Please make read.unenriched TRUE or supply a list of unenriched genes.")
  
  # Quantile normalize the extracted genes and interpolate to the other genes:
  controls2[,names(controls1)] <- get_quantile(as.matrix(controls1))
  normed <- cbind(gene_reps[,which(colnames(gene_reps)%in%c("Gene","Category")),drop=F],gene_reps[,c(samples1,samples2),drop=F])
  for(i in c(samples1,samples2)) {
    QQ <- as.data.frame(stats::qqplot(x=controls1[,i],y=controls2[,i],plot.it=FALSE))
    fit <- stats::smooth.spline(x=QQ$x,y=QQ$y,spar=1)
    normed[,i] <- stats::predict(fit,gene_reps[,i])$y
  }
  # Quantile normalize the sgRNAs targeting the extracted genes and interpolate to the other sgRNAs:
  controls2_sgRNA[,names(controls1_sgRNA)] <- get_quantile(as.matrix(controls1_sgRNA))
  normed_sgRNA <- cbind(sgRNA1[,which(colnames(sgRNA1)%in%c("sgRNA","Gene","Category")),drop=F],sgRNA1[,cond_group1,drop=F],sgRNA2[,cond_group2,drop=F])
  colnames(normed_sgRNA)[which(colnames(normed_sgRNA)==cond_group1)] <- paste0(cond_group1,"_biased")
  colnames(normed_sgRNA)[which(colnames(normed_sgRNA)==cond_group2)] <- paste0(cond_group2,"_biased")
  normed_sgRNA[,cond_group1] <- sgRNA1[,cond_group1]
  normed_sgRNA[,cond_group2] <- sgRNA2[,cond_group2]
  for(i in c(cond_group1,cond_group2)) {
    QQ <- as.data.frame(stats::qqplot(x=controls1_sgRNA[,i],y=controls2_sgRNA[,i],plot.it=FALSE))
    fit <- stats::smooth.spline(x=QQ$x,y=QQ$y,spar=1)
    normed_sgRNA[,i] <- stats::predict(fit,sgRNA[,i])$y
  }
  # Replicate average, Z score, p value and FDR -----------------------------------------------------------------------------
  print("Computing Z score...")
  if(!is.null(shinyF)) shinyF(0.2,message='Differential analysis',detail="Computing Z score...")
  # Averaged biased scores (only used for visualization):
  # scored <- cbind(scored_reps0[,which(colnames(scored_reps0)%in%c("Gene","Category")),drop=F],
  #                 rowMeans(scored_reps0[,samples1,drop=FALSE]),
  #                 rowMeans(scored_reps0[,samples2,drop=FALSE]))
  # colnames(scored)[(ncol(scored)-1):ncol(scored)] <- c(condition1,condition2)
  # Averaged unbiased scores:
  averaged <- cbind(gene1[,which(colnames(gene1)%in%c("Gene","Category")),drop=F],gene1[,cond_group1,drop=FALSE],gene2[,cond_group2,drop=FALSE])
  colnames(averaged)[which(colnames(averaged)==cond_group1)] <- paste0(cond_group1,"_biased")
  colnames(averaged)[which(colnames(averaged)==cond_group2)] <- paste0(cond_group2,"_biased")
  averaged = averaged[match(unenriched, averaged$Gene),]
  averaged[,cond_group1] <- rowMeans(normed[,samples1,drop=FALSE])
  averaged[,cond_group2] <- rowMeans(normed[,samples2,drop=FALSE])
  # Z score and t test with FDR:
  N1 <- length(samples1); N2 <- length(samples2)
  analyzed <- cbind(averaged,Z=averaged[,cond_group1]-averaged[,cond_group2])
  analyzed$Z <- (analyzed$Z-stats::median(analyzed$Z)) / stats::mad(analyzed$Z,constant=1.4826) #the Z score is estimated by the MAD
  analyzed$`P(-)` <- stats::pnorm(analyzed$Z,lower.tail=TRUE)
  analyzed$`FDR(-)` <- stats::p.adjust(analyzed$`P(-)`,"fdr")
  analyzed$`P(+)` <- stats::pnorm(-1*analyzed$Z,lower.tail=TRUE)
  analyzed$`FDR(+)` <- stats::p.adjust(analyzed$`P(+)`,"fdr")
  if(N1>1 & N2>1) {
    # print(N1)
    # print(N2)
    # print(head(normed[,-which(colnames(normed)%in%c("Gene","Category"))]))
    analyzed$`P(replicates)` <- apply(normed[,-which(colnames(normed)%in%c("Gene","Category"))],1,
                                           function(x)stats::t.test(x[1:N1],x[(N1+1):(N1+N2)])$p.value)
    analyzed$`FDR(replicates)` <- stats::p.adjust(analyzed$`P(replicates)`,"fdr")
  }
  # P value from normalized sgRNAs:
  print("Computing P value...")
  if(!is.null(shinyF)) shinyF(0.2,message='Differential analysis',detail="Computing P value...")
  normed_sgRNA$Z <- normed_sgRNA[,cond_group1]-normed_sgRNA[,cond_group2]
  normed_sgRNA$Z <- (normed_sgRNA$Z-stats::median(normed_sgRNA$Z)) / stats::mad(normed_sgRNA$Z,constant=1.4826) #the Z score is estimated by the MAD
  p_sgRNA <- getPValues(normed_sgRNA$Gene,normed_sgRNA$sgRNA,normed_sgRNA$Z,0.5)
  colnames(p_sgRNA)[ncol(p_sgRNA)] <- "P(sgRNAs)"
  analyzed <- merge(analyzed,p_sgRNA[,c("Gene","P(sgRNAs)")])
  analyzed$`FDR(sgRNAs)` <- stats::p.adjust(analyzed$`P(sgRNAs)`,"fdr")
  analyzed <- analyzed[order(analyzed$Z),]
  # Output  --------------------------------------------------------------------------------------------------------------
  if(!is.null(id)) {
    utils::write.table(normed_sgRNA,paste0(id,"/",cond_group1,"_",cond_group2,"_sgRNA.txt"),quote=FALSE,sep='\t',row.names=FALSE,col.names=TRUE)
    # utils::write.table(normed,paste0(id,"/",cond_group1,"_",cond_group2,"_normalized_reps.txt"),quote=FALSE,sep='\t',row.names=FALSE,col.names=TRUE)
    utils::write.table(analyzed,paste0(id,"/",cond_group1,"_",cond_group2,"_differential.txt"),quote=FALSE,sep='\t',row.names=FALSE,col.names=TRUE)
    if(report==TRUE) {
      if("plotly" %in% rownames(utils::installed.packages()) == TRUE) {
        print("Generating analysis report...")
        rmarkdown::render("rmd/differential.Rmd",output_file=paste0(cond_group1,"_",cond_group2,"_differential.html"),output_dir=id,#intermediates_dir=id,knit_root_dir=id,
                          params = list( #paste0(getwd(),"/",id)
                            condition1 = cond_group1,
                            condition2 = cond_group2,
                            # scored = averaged,
                            analyzed = analyzed
                          ))
      } else print("plotly installation not found.")
    }
  }
  print("Done.")
  return(list(sgRNA=normed_sgRNA,Gene=analyzed))
}


